title: FSCD 2026 @ Lisbon.
description: 11th International Conference on Formal Structures for Computation and Deduction 20 - 23 July 2026

baseurl: 
url: https://fscd2026.github.io

permalink: pretty
theme: jekyll-nagymaros

home: /
copyright: DCC@FCUP
indexing: true

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  